name: course_finder
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  modal_progress_hud: ^0.1.3
  http: ^0.12.0+2
  intl: ^0.16.0
  shared_preferences: ^0.5.3
  material_design_icons_flutter: ^3.2.4595
  flutter_vector_icons: ^0.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Stalemate
      fonts:
        - asset: fonts/Stalemate-Regular.ttf
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
    - family: NotoSansSC
      fonts:
        - asset: fonts/NotoSansSC-Regular.otf
