name: course_finder
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  modal_progress_hud: ^0.1.3
  http: ^0.12.0+2
  intl: ^0.16.0
  shared_preferences: ^0.5.3
  material_design_icons_flutter: ^3.2.4595
  flutter_vector_icons: ^0.2.1
  outline_material_icons: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Stalemate
      fonts:
        - asset: fonts/Stalemate-Regular.ttf
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
    - family: NotoSansSC
      fonts:
        - asset: fonts/NotoSansSC-Regular.otf
  # To add assets to your application, add an assets section, like this:
  assets:
   - images/